### ISSUE TITLE
bug after logon

### ISSUE THREAD

**Issue by sea5kg** [LoinASD/console_client#19]
./console-client.py
Email: freehackquest@gmail.com
Password:
Traceback (most recent call last):
  File "./console-client.py", line 234, in <module>
    fhq.login()
  File "./console-client.py", line 52, in login
    if not self.api.security.login(self.email, self.password): exit(1)
  File "/root/console_client.git/FHQFrontEndLib.py", line 22, in login
    resp = self.parent.sendrequest('/security/login.php', {"email": email, "password": password})
  File "/root/console_client.git/FHQFrontEndLib.py", line 119, in sendrequest
    resp = r.json()
TypeError: 'dict' object is not callable

**Comment by sea5kg** [comment]
root# cat /etc/_release_
PRETTY_NAME="Debian GNU/Linux 7 (wheezy)"
NAME="Debian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="http://bugs.debian.org/"
root# python --version
Python 2.7.3
