### ISSUE TITLE
unstable

### ISSUE THREAD

**Issue by sea5kg** [LoinASD/console_client#22]
/> ql
5) FHQ 2014                  jeopardy
8) FHQ 2015                  jeopardy
3) FHQ 2012                  jeopardy
2) ASIS Quals CTF 2015       jeopardy
1) freehackquest-big-game    jeopardy
7) SibirCTF 2014 J           jeopardy
4) FHQ 2013                  jeopardy
6) Plaid CTF 2014            jeopardy
Please choose game: chg 8
Traceback (most recent call last):
  File "./console-client.py", line 257, in <module>
    fhq.allFunc[i](scmd)
  File "./console-client.py", line 104, in quests_list
    self.choose_game()
  File "./console-client.py", line 96, in choose_game
    choosed_gameid = int(raw_input("Please choose game: "))
ValueError: invalid literal for int() with base 10: 'chg 8'

**Comment by sea5kg** [comment]
Если ввели всякую фигню а не цифру надо что бы программа не вылетала
